// @aegis/zapier — Zapier CLI app. STUB.
//
// The real implementation is generated by `zapier init` and lives as a
// separate package. This src/index.ts is a placeholder describing the
// shape of the action contract.

export interface ZapierVerifyInput {
  apiKey: string;
  agentToken: string;
  action: string;
  amount?: number;
}

export interface ZapierVerifyOutput {
  valid: boolean;
  trustScore?: number;
  trustBand?: string;
  reason?: string;
  auditEventId?: string;
}

/**
 * Reference for the Zapier action's `perform()` function. STUB.
 */
export async function performVerify(
  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  input: ZapierVerifyInput,
): Promise<ZapierVerifyOutput> {
  // TODO(peer aegis:int-zapier): real implementation uses Zapier's
  // `z.request()` to call POST /v1/verify with proper auth.
  return { valid: false, reason: 'NOT_IMPLEMENTED' };
}
