// Cross-package parity — DENIAL_REASON_PRECEDENCE across FOUR surfaces.
//
//   1. Canonical       — `packages/types/src/constants.ts` (TS source of truth)
//   2. sdk-ts gen      — `packages/sdk-ts/src/denial-reason.generated.ts`
//                        (gated by `denial-reason-parity.spec.ts`)
//   3. sdk-py gen      — `packages/sdk-py/aegis/_denial_reason_generated.py`
//                        (NEW — emitted alongside the TS gen by
//                        `scripts/generate-denial-reason.ts`)
//   4. sdk-py re-export — `packages/sdk-py/aegis/{_constants,models}.py`
//                        (re-exports surface #3 so public consumers don't
//                        depend on the private generated module)
//
// PRIMARY GATE: `pnpm check:denial-reason-gen` — re-runs the generator
// and asserts the committed bytes equal the freshly-generated bytes.
// That is the *structural* parity contract; once the generator runs
// in CI, surfaces #2 and #3 cannot drift from surface #1 by definition.
//
// THIS SPEC: belt-and-braces against HAND EDITS to the generated Py
// file. A contributor who edits `_denial_reason_generated.py` directly
// (instead of re-running the generator) would defeat the structural
// gate's first-line — this spec catches it on second pass by parsing
// the generated file and comparing to the canonical TS tuple.
//
// Also asserts the re-export surface (#4) actually re-exports from the
// generated module: if someone re-introduces a hand-maintained tuple
// in `_constants.py` or `models.py`, the regex parsers below fail
// loudly (no longer finds the literal tuple/class).
//
// SEV-1: any failure here means a Python relying-party SDK either:
//   (a) cannot decode a denial reason the API returned (silent fall-through
//       to "unknown" — the exact failure mode the precedence tuple was
//       designed to prevent), or
//   (b) does not know about a newer reason at all (no exhaustive match/case
//       protection — Python consumers think they handle every case but
//       silently miss a newly-added reason).
//
// Mechanism: read the canonical TS tuple via module import; parse the
// generated Py file as text (no Python child process — keeps the test
// fast and CI-portable). The regex parsers are deliberately narrow and
// break loudly if the generated file shape changes — that's the
// intended behavior; the generator's renderPy() is the contract.

import { readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { describe, expect, it } from 'vitest';

import { DENIAL_REASON_PRECEDENCE } from '../../packages/types/src/constants';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const REPO_ROOT = resolve(__dirname, '..', '..');

const PY_GENERATED = resolve(REPO_ROOT, 'packages/sdk-py/aegis/_denial_reason_generated.py');
const PY_CONSTANTS = resolve(REPO_ROOT, 'packages/sdk-py/aegis/_constants.py');
const PY_MODELS = resolve(REPO_ROOT, 'packages/sdk-py/aegis/models.py');

/**
 * Parse the ordered DENIAL_REASON_PRECEDENCE tuple from the generated
 * Py module. Matches the literal:
 *   DENIAL_REASON_PRECEDENCE: Final[tuple[str, ...]] = (
 *       "PLAN_LIMIT_EXCEEDED",
 *       ...
 *   )
 */
function parsePyConstantsTuple(source: string): string[] {
  const tupleMatch = source.match(
    /DENIAL_REASON_PRECEDENCE\s*:\s*Final\[tuple\[str,\s*\.\.\.\]\]\s*=\s*\(([\s\S]*?)\)/,
  );
  if (!tupleMatch) {
    throw new Error(
      `denial-reason-sdk-py-parity: could not locate DENIAL_REASON_PRECEDENCE tuple ` +
        `in _denial_reason_generated.py — file shape changed? Update the parser in this spec ` +
        `(and the matching renderPy() in scripts/generate-denial-reason.ts).`,
    );
  }
  return [...tupleMatch[1]!.matchAll(/"([A-Z_]+)"/g)].map((m) => m[1]!);
}

/**
 * Parse the ordered DenialReason StrEnum members from `models.py`.
 * Matches the literal:
 *   class DenialReason(StrEnum):
 *       PLAN_LIMIT_EXCEEDED = "PLAN_LIMIT_EXCEEDED"
 *       ...
 *
 * Captures the entire class body — from `class DenialReason(...):` up
 * to (but not including) the next TOP-LEVEL `class ` declaration, or
 * end of file. Blank lines INSIDE the class (e.g. between the doc
 * comment block and the first member) are tolerated; the member
 * regex below filters them out by indent + identifier-shape match.
 */
function parsePyEnumMembers(source: string): string[] {
  const classMatch = source.match(
    /class\s+DenialReason\s*\(\s*StrEnum\s*\)\s*:\s*\n([\s\S]*?)(?=\n^class\s|$(?![\s\S]))/m,
  );
  if (!classMatch) {
    throw new Error(
      `denial-reason-sdk-py-parity: could not locate DenialReason class in models.py — ` +
        `file shape changed? Update the parser in this spec.`,
    );
  }
  const memberRegex = /^\s{4}([A-Z_]+)\s*=\s*"([A-Z_]+)"/gm;
  const out: string[] = [];
  for (const m of classMatch[1]!.matchAll(memberRegex)) {
    // Sanity: name MUST equal value (str-enum invariant); StrEnum
    // members where the symbol diverges from the wire string would
    // silently produce a different denial token on the wire.
    if (m[1] !== m[2]) {
      throw new Error(
        `denial-reason-sdk-py-parity: DenialReason.${m[1]} value "${m[2]}" diverges ` +
          `from its symbol name. StrEnum members must be self-equal so the wire ` +
          `string matches the Python identifier; otherwise serialization drifts ` +
          `silently from the API contract.`,
      );
    }
    out.push(m[1]!);
  }
  return out;
}

describe('denial-reason cross-package parity (sdk-py generated + re-exports)', () => {
  const pyGeneratedSrc = readFileSync(PY_GENERATED, 'utf8');
  const pyConstantsSrc = readFileSync(PY_CONSTANTS, 'utf8');
  const pyModelsSrc = readFileSync(PY_MODELS, 'utf8');

  // Parse the generated file — the new source of truth post-Plan-A.
  const pyTuple = parsePyConstantsTuple(pyGeneratedSrc);
  const pyEnum = parsePyEnumMembers(pyGeneratedSrc);

  it('generated DENIAL_REASON_PRECEDENCE equals canonical TS (same order, same length)', () => {
    // If this fails: someone hand-edited _denial_reason_generated.py
    // instead of editing canonical TS + re-running the generator.
    // Defeats the structural CI gate (`pnpm check:denial-reason-gen`).
    // Fix: revert the hand edit, update packages/types/src/constants.ts
    // and re-run `pnpm gen:denial-reason`.
    expect(pyTuple).toEqual([...DENIAL_REASON_PRECEDENCE]);
  });

  it('generated DenialReason members equal canonical TS (same order, same length)', () => {
    expect(pyEnum).toEqual([...DENIAL_REASON_PRECEDENCE]);
  });

  it('every canonical reason is present in the generated tuple AND enum', () => {
    for (const r of DENIAL_REASON_PRECEDENCE) {
      expect(pyTuple).toContain(r);
      expect(pyEnum).toContain(r);
    }
  });

  it('generated tuple+enum have no extras not in the canonical tuple', () => {
    for (const r of pyTuple) expect(DENIAL_REASON_PRECEDENCE as readonly string[]).toContain(r);
    for (const r of pyEnum) expect(DENIAL_REASON_PRECEDENCE as readonly string[]).toContain(r);
  });

  it('generated tuple and enum agree with each other (intra-file)', () => {
    // Sanity: the generator emits both from the same source array, so
    // divergence here means the generator itself broke between renderPy's
    // two emit blocks. Tightly impossible by construction, but cheap to
    // assert.
    expect(pyTuple).toEqual(pyEnum);
  });

  it('parsed generated tuple contains no duplicates', () => {
    expect(new Set(pyTuple).size).toBe(pyTuple.length);
  });

  it('parsed generated enum contains no duplicates', () => {
    expect(new Set(pyEnum).size).toBe(pyEnum.length);
  });

  // Negative-control on the parser: if either parser silently returns
  // an empty array (e.g. because someone changed the file format), the
  // test would falsely pass `[]` == `[...DENIAL_REASON_PRECEDENCE]`
  // when canonical is also empty — guard against that.
  it('parsers extract a non-empty list (sanity — guards against silent empty parse)', () => {
    expect(pyTuple.length).toBeGreaterThan(0);
    expect(pyEnum.length).toBeGreaterThan(0);
    expect((DENIAL_REASON_PRECEDENCE as readonly string[]).length).toBeGreaterThan(0);
  });

  // ── Re-export surface contracts ─────────────────────────────────────────
  //
  // `_constants.py` and `models.py` are the PUBLIC consumer-facing modules.
  // After Plan A, they re-export from `_denial_reason_generated.py` rather
  // than declaring literals. Lock those re-exports: a future contributor
  // who re-introduces a hand-maintained tuple/enum in either public module
  // would re-create the drift class Plan A was designed to eliminate.

  it('_constants.py re-exports DENIAL_REASON_PRECEDENCE from the generated module', () => {
    expect(pyConstantsSrc).toMatch(
      /from\s+\._denial_reason_generated\s+import\s+DENIAL_REASON_PRECEDENCE\b/,
    );
    // Negative: no literal tuple definition in _constants.py.
    expect(pyConstantsSrc).not.toMatch(/DENIAL_REASON_PRECEDENCE\s*:\s*Final\[tuple\[str/);
  });

  it('models.py re-exports DenialReason from the generated module', () => {
    expect(pyModelsSrc).toMatch(
      /from\s+\._denial_reason_generated\s+import\s+DenialReason\b/,
    );
    // Negative: no class DenialReason(StrEnum) definition in models.py.
    expect(pyModelsSrc).not.toMatch(/class\s+DenialReason\s*\(\s*StrEnum\s*\)/);
  });

  it('generated file carries the @generated marker (rejects hand edits)', () => {
    expect(pyGeneratedSrc).toMatch(/@generated/);
    expect(pyGeneratedSrc).toMatch(/pnpm gen:denial-reason/);
  });
});
