#!/usr/bin/env bash
# 10-rename-checkout.sh — apply text substitution + path renames in the
# current checkout. Idempotent.
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"
CURRENT_BRANCH="$(git rev-parse --abbrev-ref HEAD)"
echo "[rename] branch=$CURRENT_BRANCH"

#
# 1. TEXT SUBSTITUTION
#
# Three case-sensitive passes. Order doesn't matter for correctness because
# each replacement target is distinct, but mixed-case first reads more naturally
# in logs.
#
# Exclusions:
#   - .git/                       (obvious)
#   - node_modules/, dist/, build/, .next/, .turbo/, coverage/, .yarn/
#   - apps/api/prisma/migrations/ (immutable per CLAUDE.md; we add a new one)
#   - pnpm-lock.yaml              (regenerated by pnpm install)
#   - any binary file
#
# We list tracked text files via `git ls-files` and skip binaries with
# `file --mime`.
#

echo "[rename] [1/3] text substitution"

git ls-files \
  | grep -Ev '^(apps/api/prisma/migrations/|pnpm-lock\.yaml$|\.yarn/|node_modules/|dist/|build/|\.next/|\.turbo/|coverage/)' \
  | grep -Ev '\.(png|jpg|jpeg|gif|ico|webp|pdf|docx|xlsx|pptx|woff2?|ttf|otf|eot|zip|tar|gz|bz2|7z|mp3|mp4|mov|webm|class|jar|so|dylib|dll|exe|wasm)$' \
  | while IFS= read -r f; do
      [ -f "$f" ] || continue
      # quick binary guard
      if file --mime "$f" 2>/dev/null | grep -q 'charset=binary'; then continue; fi
      # use perl for portable in-place edit (GNU sed -i and BSD sed -i differ)
      perl -i -pe 's/AEGIS/OKORO/g; s/Aegis/Okoro/g; s/aegis/okoro/g' "$f"
    done

#
# 2. FILE & DIRECTORY RENAMES
#
# Process deepest paths first so renaming a parent directory doesn't break
# child paths still on the queue.
#
echo "[rename] [2/3] path renames"

# Build list, sort by depth desc, then alpha
mapfile -t paths_to_rename < <(git ls-files | grep -i 'aegis' | awk -F/ '{print NF "\t" $0}' | sort -rn -k1,1 | cut -f2)

for old in "${paths_to_rename[@]}"; do
  new="$(printf '%s' "$old" | perl -pe 's/AEGIS/OKORO/g; s/Aegis/Okoro/g; s/aegis/okoro/g')"
  if [ "$old" = "$new" ]; then continue; fi
  if [ ! -e "$old" ]; then continue; fi
  mkdir -p "$(dirname "$new")"
  # use git mv when possible to preserve history
  if git mv -k "$old" "$new" 2>/dev/null; then
    echo "  git mv $old -> $new"
  else
    mv "$old" "$new"
    git add -A "$(dirname "$new")"
    echo "  mv     $old -> $new"
  fi
done

# Empty parent dirs left behind (e.g., packages/sdk-py/aegis/ after files moved)
find . -type d -empty -not -path './.git/*' -not -path './node_modules/*' -print -delete 2>/dev/null || true

#
# 3. SUMMARY
#
echo "[rename] [3/3] summary for $CURRENT_BRANCH"
REMAINING=$(git grep -i -c 'aegis' 2>/dev/null | awk -F: '{s+=$NF} END {print s+0}')
echo "[rename] remaining aegis matches (case-insensitive): $REMAINING"
if [ "$REMAINING" -gt 0 ]; then
  echo "[rename] (expected: matches inside pnpm-lock.yaml and existing migrations only)"
  echo "[rename] sample of remaining files:"
  git grep -l -i 'aegis' 2>/dev/null | head -20
fi
