#!/usr/bin/env bash
# 20-rename-all-branches.sh — loop over every local branch, run the rename,
# commit per branch. Skips branches that are checked out in another worktree
# (git would refuse the checkout anyway).
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LOG_DIR="$(git rev-parse --show-toplevel)/.rename-log"
mkdir -p "$LOG_DIR"

ORIGINAL_BRANCH="$(git rev-parse --abbrev-ref HEAD)"
echo "[sweep] starting from $ORIGINAL_BRANCH"

# Branches in use elsewhere (in any worktree besides the main one)
mapfile -t SKIP_BRANCHES < <(
  git worktree list --porcelain \
    | awk '/^worktree/ {wt=$2} /^branch/ {if (wt != "'"$(git rev-parse --show-toplevel)"'") print $2}' \
    | sed 's|^refs/heads/||'
)

is_skipped() {
  local b=$1
  for s in "${SKIP_BRANCHES[@]:-}"; do
    [ "$b" = "$s" ] && return 0
  done
  return 1
}

# All local branches
mapfile -t ALL_BRANCHES < <(git for-each-ref --format='%(refname:short)' refs/heads/)

SKIPPED_LOG="$LOG_DIR/skipped-branches-$(date +%Y%m%d-%H%M%S).txt"
FAILED_LOG="$LOG_DIR/failed-branches-$(date +%Y%m%d-%H%M%S).txt"
SUCCESS_LOG="$LOG_DIR/renamed-branches-$(date +%Y%m%d-%H%M%S).txt"
: > "$SKIPPED_LOG"; : > "$FAILED_LOG"; : > "$SUCCESS_LOG"

for branch in "${ALL_BRANCHES[@]}"; do
  if [ "$branch" = "$ORIGINAL_BRANCH" ]; then
    echo "[sweep] $branch — already renamed (current branch)"
    echo "$branch" >> "$SUCCESS_LOG"
    continue
  fi
  if is_skipped "$branch"; then
    echo "[sweep] $branch — SKIPPED (active worktree)"
    echo "$branch" >> "$SKIPPED_LOG"
    continue
  fi

  echo "[sweep] $branch — checking out"
  if ! git checkout "$branch" 2>&1; then
    echo "[sweep] $branch — checkout FAILED, skipping"
    echo "$branch" >> "$FAILED_LOG"
    continue
  fi

  # Run the rename. If it fails, log and continue.
  if ! bash "$SCRIPT_DIR/10-rename-checkout.sh"; then
    echo "[sweep] $branch — rename FAILED"
    echo "$branch" >> "$FAILED_LOG"
    git reset --hard
    continue
  fi
  bash "$SCRIPT_DIR/40-emit-prisma-migration.sh" || true

  git add -A
  if git diff --cached --quiet; then
    echo "[sweep] $branch — no changes, skipping commit"
  else
    if git commit --no-verify -m "chore: rename aegis to okoro

Generated by scripts/rename-aegis-to-okoro/.

Constraint: pnpm-lock.yaml not regenerated; existing migrations untouched.
Tested: text substitution and path renames.
Not-tested: pnpm install, pnpm check.
Scope-risk: high — touches every workspace."; then
      echo "[sweep] $branch — committed"
      echo "$branch" >> "$SUCCESS_LOG"
    else
      echo "[sweep] $branch — commit FAILED"
      echo "$branch" >> "$FAILED_LOG"
    fi
  fi
done

echo "[sweep] returning to $ORIGINAL_BRANCH"
git checkout "$ORIGINAL_BRANCH"

echo
echo "[sweep] DONE"
echo "  renamed: $(wc -l < "$SUCCESS_LOG") branches  -> $SUCCESS_LOG"
echo "  skipped: $(wc -l < "$SKIPPED_LOG") branches  -> $SKIPPED_LOG"
echo "  failed:  $(wc -l < "$FAILED_LOG") branches  -> $FAILED_LOG"
