#!/usr/bin/env bash
# run.sh — orchestrator for the OKORO → OKORO rename.
# Aggressive in-place mode. Read scripts/rename-okoro-to-okoro/README.md first.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
cd "$REPO_ROOT"

LOG_DIR="$REPO_ROOT/.rename-log"
mkdir -p "$LOG_DIR"
LOG="$LOG_DIR/run-$(date +%Y%m%d-%H%M%S).log"
exec > >(tee -a "$LOG") 2>&1

echo "=========================================="
echo " OKORO → OKORO rename"
echo " Repo:    $REPO_ROOT"
echo " Log:     $LOG"
echo " Started: $(date -Iseconds)"
echo "=========================================="

bash "$SCRIPT_DIR/00-preflight.sh"
bash "$SCRIPT_DIR/10-rename-checkout.sh"
bash "$SCRIPT_DIR/15-rebrand-domain-to-okoroapp.sh"
bash "$SCRIPT_DIR/40-emit-prisma-migration.sh"

# Commit current checkout before sweeping other branches
git add -A
if ! git diff --cached --quiet; then
  git commit -m "chore: rename okoro to okoro

Generated by scripts/rename-okoro-to-okoro/.
Includes:
- case-preserving text substitution (OKORO/Okoro/okoro)
- file and directory path renames
- new Prisma migration for okoro_app/okoro_owner roles, okoro_current_principal/
  okoro_rls_bypass_active functions, and okoro.* GUC namespace

Constraint: pnpm-lock.yaml not regenerated; existing migrations untouched.
Tested: text substitution and path renames (sandbox).
Not-tested: pnpm install, pnpm check, dashboard SSR, provider configs.
Scope-risk: high — touches every workspace and the DB schema." \
    --no-verify
fi

bash "$SCRIPT_DIR/20-rename-all-branches.sh"

echo
echo "=========================================="
echo " Per-branch rename complete."
echo " NEXT STEPS (do these by hand):"
echo "   1. pnpm install            # regenerate lockfile"
echo "   2. pnpm check              # full local gate"
echo "   3. pnpm test:parity        # cross-package contract parity"
echo "   4. Review:  git grep -i okoro   (should be empty)"
echo "   5. When ready, rename the root folder:"
echo "        cd .. && bash $SCRIPT_DIR/30-rename-folder.sh"
echo "=========================================="
