"""AEGIS Python SDK — neutral identity & verification layer for AI agents.

Public surface:

- :class:`AsyncAegis` — primary async client
- :class:`Aegis` — sync wrapper (uses ``asyncio.run`` per call)
- :func:`generate_keypair` / :func:`sign_agent_token` / :func:`decode_unsafe`
  / :func:`verify_agent_token` — local crypto helpers
- :class:`AegisError` and the typed subtree (:class:`ValidationError`,
  :class:`AuthError`, :class:`NotFoundError`, :class:`RateLimitedError`,
  :class:`ServerError`, :class:`NetworkError`, :class:`ConflictError`)
- All wire models (:class:`AgentRecord`, :class:`PolicyRecord`,
  :class:`VerifyResult`, …) and enums (:class:`TrustBand`,
  :class:`DenialReason`, …)
"""

from __future__ import annotations

from ._version import __version__
from .client import Aegis, AsyncAegis
from .intent import IntentClient
from .verify_cache import (
    CachedVerify,
    MemoryVerifyCache,
    VerifyCache,
    VerifyCacheContext,
    build_cache_key,
    clamp_ttl_ms,
)
from .verify_gateway import (
    AsyncVerifyGateway,
    BreakerState,
    FallbackMode,
    VerifyGateway,
    VerifyGatewayHooks,
    VerifyGatewayMetrics,
    VerifyGatewayOptions,
)
from .crypto import (
    Keypair,
    SignContext,
    b64u_decode,
    b64u_encode,
    decode_unsafe,
    generate_keypair,
    sign_agent_token,
    verify_agent_token,
)
from .errors import (
    AegisError,
    AuthError,
    ConflictError,
    NetworkError,
    NotFoundError,
    RateLimitedError,
    ServerError,
    ValidationError,
)
from .webhook import (
    DEFAULT_TOLERANCE_SECONDS,
    WEBHOOK_DELIVERY_ID_HEADER,
    WEBHOOK_EVENT_HEADER,
    WEBHOOK_SIGNATURE_HEADER,
    VerifiedWebhook,
    WebhookSignatureInvalidError,
    WebhookSignatureMalformedError,
    WebhookTimestampError,
    verify_webhook_signature,
)
from .webhook_replay import (
    DEFAULT_REPLAY_TTL_SECONDS,
    ReplayVerdict,
    WebhookReplayDetectedError,
    WebhookReplayStore,
    assert_not_replay,
    create_memory_replay_store,
)
from .webhook_events import (
    AgentAnomalyDetectedEvent,
    AgentAnomalyDetectedPayload,
    AgentFlaggedByRelyingPartyEvent,
    AgentFlaggedByRelyingPartyPayload,
    AgentPolicyExpiredEvent,
    AgentPolicyExpiredPayload,
    AgentRevokedEvent,
    AgentRevokedPayload,
    AgentTrustScoreChangedEvent,
    AgentTrustScoreChangedPayload,
    WebhookEnvelope,
    WebhookEventName,
    WebhookEventParseError,
    interpret_webhook_event,
    is_webhook_envelope,
)
from .models import (
    AgentPolicy,
    AgentRecord,
    AgentRegistrationRequest,
    AgentRegistrationResponse,
    AgentRuntime,
    AgentStatus,
    AgentStatusResponse,
    AuditDecision,
    AuditEvent,
    AuditLogResponse,
    Currency,
    DenialReason,
    PolicyCategory,
    PolicyCreateRequest,
    PolicyRecord,
    PolicyScope,
    PolicyStatus,
    ReportAccepted,
    ReportEventType,
    ReportRequest,
    SignalSeverity,
    SpendLimit,
    TrustBand,
    VerifyRequest,
    VerifyResult,
    VerifySpendRemaining,
)

__all__ = [
    "Aegis",
    "AegisError",
    "AsyncVerifyGateway",
    "BreakerState",
    "CachedVerify",
    "FallbackMode",
    "MemoryVerifyCache",
    "VerifyCache",
    "VerifyCacheContext",
    "VerifyGateway",
    "VerifyGatewayHooks",
    "VerifyGatewayMetrics",
    "VerifyGatewayOptions",
    "build_cache_key",
    "clamp_ttl_ms",
    "AgentPolicy",
    "AgentRecord",
    "AgentRegistrationRequest",
    "AgentRegistrationResponse",
    "AgentRuntime",
    "AgentStatus",
    "AgentStatusResponse",
    "AsyncAegis",
    "AuditDecision",
    "AuditEvent",
    "AuditLogResponse",
    "AuthError",
    "ConflictError",
    "Currency",
    "DenialReason",
    "IntentClient",
    "Keypair",
    "NetworkError",
    "NotFoundError",
    "PolicyCategory",
    "PolicyCreateRequest",
    "PolicyRecord",
    "PolicyScope",
    "PolicyStatus",
    "RateLimitedError",
    "ReportAccepted",
    "ReportEventType",
    "ReportRequest",
    "ServerError",
    "SignContext",
    "SignalSeverity",
    "SpendLimit",
    "TrustBand",
    "ValidationError",
    "VerifyRequest",
    "VerifyResult",
    "VerifySpendRemaining",
    "DEFAULT_TOLERANCE_SECONDS",
    "VerifiedWebhook",
    "WEBHOOK_DELIVERY_ID_HEADER",
    "WEBHOOK_EVENT_HEADER",
    "WEBHOOK_SIGNATURE_HEADER",
    "WebhookSignatureInvalidError",
    "WebhookSignatureMalformedError",
    "WebhookTimestampError",
    "verify_webhook_signature",
    "DEFAULT_REPLAY_TTL_SECONDS",
    "ReplayVerdict",
    "WebhookReplayDetectedError",
    "WebhookReplayStore",
    "assert_not_replay",
    "create_memory_replay_store",
    "AgentAnomalyDetectedEvent",
    "AgentAnomalyDetectedPayload",
    "AgentFlaggedByRelyingPartyEvent",
    "AgentFlaggedByRelyingPartyPayload",
    "AgentPolicyExpiredEvent",
    "AgentPolicyExpiredPayload",
    "AgentRevokedEvent",
    "AgentRevokedPayload",
    "AgentTrustScoreChangedEvent",
    "AgentTrustScoreChangedPayload",
    "WebhookEnvelope",
    "WebhookEventName",
    "WebhookEventParseError",
    "interpret_webhook_event",
    "is_webhook_envelope",
    "__version__",
    "b64u_decode",
    "b64u_encode",
    "decode_unsafe",
    "generate_keypair",
    "sign_agent_token",
    "verify_agent_token",
]
