"""Shared constants — mirrors ``packages/types/src/constants.ts``.

Importing the same constant from a Python client vs. the API guarantees they
agree on enum names, header names, and TTL boundaries.
"""

from __future__ import annotations

from typing import Final

# ── HTTP headers ─────────────────────────────────────────────
AEGIS_HEADER_API_KEY: Final[str] = "X-AEGIS-API-Key"
AEGIS_HEADER_VERIFY_KEY: Final[str] = "X-AEGIS-Verify-Key"
AEGIS_HEADER_REQUEST_ID: Final[str] = "X-Request-Id"
AEGIS_HEADER_TOKEN: Final[str] = "X-AEGIS-Token"
AEGIS_HEADER_SIGNATURE: Final[str] = "X-AEGIS-Signature"
AEGIS_HEADER_IDEMPOTENCY: Final[str] = "Idempotency-Key"

# ── Trust band thresholds (lower bound, inclusive) ───────────
TRUST_BAND_THRESHOLDS: Final[dict[str, int]] = {
    "PLATINUM": 750,
    "VERIFIED": 500,
    "WATCH": 250,
    "FLAGGED": 0,
}

# ── Token TTL ────────────────────────────────────────────────
TOKEN_TTL_MIN_SECONDS: Final[int] = 30
TOKEN_TTL_MAX_SECONDS: Final[int] = 60
TOKEN_TTL_DEFAULT_SECONDS: Final[int] = 60
POLICY_TTL_MAX_DAYS: Final[int] = 365

# ── Verify-response cache TTL ────────────────────────────────
VERIFY_RESULT_DEFAULT_TTL_SECONDS: Final[int] = 30

# ── Denial reason precedence (top wins) ──────────────────────
# Re-exported from the generated module to keep TS↔PY drift
# structurally impossible. The generator
# ``scripts/generate-denial-reason.ts`` emits both
# ``packages/sdk-ts/src/denial-reason.generated.ts`` and
# ``packages/sdk-py/aegis/_denial_reason_generated.py`` from the
# canonical TS tuple in a single deterministic pass. CI gate
# ``pnpm check:denial-reason-gen`` reds on drift.
#
# Public consumers should keep importing from this module
# (``from aegis._constants import DENIAL_REASON_PRECEDENCE``) — the
# generated module is private (leading underscore) and may move
# between minor versions.
#
# Reasons in canonical precedence order (top wins). The rationale for
# each reason's position is documented in
# ``packages/types/src/constants.ts``; mirrors stay shape-only so the
# regex-based parity test catches hand edits to the generated file.
#
# PLAN_LIMIT_EXCEEDED is the billing pre-gate (fires BEFORE the
# 11-step algorithm chain). TRIAL_EXHAUSTED (ADR-0014) sits between
# SCOPE_NOT_GRANTED and SPEND_LIMIT_EXCEEDED. INTENT_MISMATCH
# (ADR-0016) is the most recent append. Adding new reasons:
# (1) append to the canonical TS tuple, (2) run
# ``pnpm gen:denial-reason``, (3) commit the regenerated bytes.
from ._denial_reason_generated import DENIAL_REASON_PRECEDENCE  # noqa: F401

# ── Webhook event names ──────────────────────────────────────
WEBHOOK_EVENT: Final[dict[str, str]] = {
    "AGENT_TRUST_SCORE_CHANGED": "aegis.agent.trust_score_changed",
    "AGENT_ANOMALY_DETECTED": "aegis.agent.anomaly_detected",
    "AGENT_POLICY_EXPIRED": "aegis.agent.policy_expired",
    "AGENT_FLAGGED_BY_RELYING_PARTY": "aegis.agent.flagged_by_relying_party",
    "AGENT_REVOKED": "aegis.agent.revoked",
}

# ── Defaults ─────────────────────────────────────────────────
DEFAULT_BASE_URL: Final[str] = "https://api.aegislabs.io/v1"
DEFAULT_TIMEOUT_MS: Final[int] = 5_000
DEFAULT_MAX_RETRIES: Final[int] = 3
RETRY_BACKOFF_MS: Final[tuple[int, ...]] = (250, 500, 1_000)
